### ISSUE TITLE
Getting no error when connecting to non existing mongo database

### ISSUE THREAD

**Issue by ygrenzinger** [mafintosh/mongojs#244]
Hello,

Everything seems fine when the db url is good but for any wrong MongoDB url there no error happening.

this is my code:
```
        mongoDB = mongojs('mongodb://1.0.0.1:23/aiguillage', ['vecteurs', 'aiguillages', 'aboProfiles']);

        mongoDB.on('ready', function () {
            logger.info('database connected');
        });

        mongoDB.on('error', function (err) {
            logger.error('connection error:' + err);
        });

        mongoDB.runCommand({ping: 1}, function (err, res) {
            if(!err && res.ok) logger.info('we\'re up');
            else throw "impossible to connect to mongodb: " + mongoDbUrl;
        });
```

Any idea ?

**Comment by woistjadefox** [comment]
Same problem here. The events 'error' and 'ready' never get fired. Even if I write down a wrong url or even if the connection is established and I'm catching data from the db.

**Comment by drudge** [comment]
+1

**Comment by jonnochoo** [comment]
yeah same for me too

**Comment by smonkey72** [comment]
couldn't even find a 'ready' in the whole repository, excepting the readme

**Comment by bubenshchykov** [comment]
+1

**Comment by peakji** [comment]
+1, and for some methods like `findAndModify` the callback is never called

**Comment by watson** [comment]
@ygrenzinger If I understand your problem correctly, you are talking about the situation where the connection string is pointing to a server that doesn't exist? It's not that the string it self isn't a valid string right?

@smonkey72 When using the `.on()` function you're adding listeners directly on an instance of either `mongodb.Server` or `mongoldb.ReplSet` (depending on your connection string). And `mongodb` is just the [mongodb-core](https://github.com/christkv/mongodb-core) module - so all events will be fired by that module.

@woistjadefox the `ready` event should not fire if the connection string is pointing to a non-existing server. I'm looking into why it never times out though

**Comment by ygrenzinger** [comment]
Yes this is the problem I found.

**Comment by smonkey72** [comment]
@watson Okay, I assumed you are using own events because there is [no `ready` event in mongodb-core](http://mongodb.github.io/node-mongodb-native/core/api/Connection.html#event:close).

Solved the issue for me:
- `ready` never gets triggered because there is no such event. Use `connect` instead.
- `error` gets not triggered when not using a connection timeout (default: `0`). To get a connection error use the option `{connectionTimeout: 5000}`

**Comment by watson** [comment]
@smonkey72 Nice catch! It's `connect` instead of `ready`. I've updated the README.md to correctly show this

**Comment by watson** [comment]
@ygrenzinger As @smonkey72 pointed out, the reason that the connection never times out is because the default timeout setting is to not time out. To have it time out and fire the `timeout` event, you'd have to explicitly set the `connectionTimeout` option. The options are given as the 3rd argument to the main mongojs function:

```js
// try to connect to MongoDB, but timeout after 5 seconds if unsuccessful
var db = mongojs('mongodb://1.0.0.1:23/mydb', ['col'], { connectionTimeout: 5000 })

db.on('timeout', function () {
  console.log('timed out when connecting to MongoDB')
})
```

I'll close this issue for now. Feel free to reopen if you're still having issues with this :smiley:

**Comment by matteocontrini** [comment]
It should be noted that the `connectionTimeout` options is [now](https://github.com/mongodb/node-mongodb-native/blob/63ec4ef433fb3a2c9fee22488cca741298618bbb/docs/reference/content/reference/faq/index.md) called `connectTimeoutMS`.
