### ISSUE TITLE
Updating value and keeping everything else

### ISSUE THREAD

**Issue by chipe13** [mafintosh/mongojs#257]
Sorry for this issue. I am not sure where else to ask. I am trying to update part of an object but keep everything else the same in the object. Here is the object in mongoDB:

```js
{
	"_id" : ObjectId("5621cc93b6b4bdc2e987087b"),
	"cardKeeperApp" : [
		{
			"data" : {
				"cardDecks" : [
					{
						"name" : "Gold Arcane",
						"searchName" : "Gold+Arcane+Playing+Cards",
						"price" : {
							"purchasePrice" : null,
							"averageWorth" : null,
							"lowWorth" : null,
							"highWorth" : null
						}
					}
				],
				"allDeckTotalWorth" : null
			}
		}
	]
}
```

I am trying to update the name key value cardKeeperApp[0].data.cardDecks[0].name

Currently it is "Gold Arcane", I cant seem to figure out how to update the name to something else. A few of the methods have come close, but the closest one seemed to delete everything that was a sibling. That was using `db.mycollection.findAndModify`

**Comment by watson** [comment]
@chipe13 It really depends on if the arrays contain multiple elements and if you only want to update one of the elements. In that case, should it only be the first element, or should it be an element that matches a specific query?

As you probably know, if you only want to update this specific document and you have the ObjectId and just want to update the first element in the `cardKeeperApp` array and inside that the first element in the `cardDecks` array, then you could use the [`$set`](http://docs.mongodb.org/manual/reference/operator/update/set/) operator together with the [`update`](http://docs.mongodb.org/manual/reference/method/db.collection.update/) command:

```js
var query = { _id: ObjectId("5621cc93b6b4bdc2e987087b") }
var update = { $set: { 'cardKeeperApp.0.data.cardDecks.0.name': 'New Name' } }
db.mycollection.update(query, update, callback)
```

But as I said it really depends on exactly what you wanna do. If you want to update all the `cardDecks` in all the documents where the name is `Gold Arcane`, it's way more problematic because to the positional operator `$` only works for one level or arrays - not two as in your case ([this is a known issue](https://jira.mongodb.org/browse/SERVER-831)).

P.S. You might try your luck on [StackOverflow](http://stackoverflow.com/questions/ask).

**Comment by chipe13** [comment]
Thanks for all the info!
