### ISSUE TITLE
How to handle authentication handling a connection pool

### ISSUE THREAD

**Issue by damibarbieri** [mafintosh/mongojs#306]
Hi there! 

First of all, great work you have done with this module! It's simple, flexible and awesome. This is not an issue, but a question. I've been reading on the best way to authenticate users against my server and how to handle the connection pool. Since I'm not sure if it is better to create a connection per new connection so as to authenticate a new user or to have connections already open and serve from them. If it is the second case, I wouldn't know how to handle the authentication process properly. I'd really appreciate an advice this is my first time struggling with user authentication and connection pooling. 

Thanks in advance!
Damian

**Comment by saintedlama** [comment]
First of all the good news is that there is no need to implement a connection pooling since mongodb-native driver in the background of mongojs already implements a connection pool.
Do you want to authenticate your users against mongodb users?

**Comment by damibarbieri** [comment]
That's cool, thanks for you quick response! Yes, my idea is to authenticate users against mongodb users collection (created for the database I want them to use). My architecture for now is a web client that after authenticating users sends messages with a json web token to a rest api (in node obviously) that persists its data in Mongo (users included there). Sorry if I was repetitive, I wanted to give you an idea of my whole panorama.

**Comment by saintedlama** [comment]
That will not scale nor really work out well since one connection (pool) created via mongojs is bound to exactly one user, that means 100 logged in users => 100 connection pools => about 500 (i guess 5 connections per pool) connections open AND you have to manage connections by hand. How will you detect that a user does not need it's server kept connection anymore?

Take a look at passport (http://passportjs.org/) to get an idea on how to handle authentication efficiently.

**Comment by saintedlama** [comment]
Perhaps you could close this issue - I guess stackoverflow is a better discussion platform than github issues :+1:

**Comment by damibarbieri** [comment]
No doubts, thanks again for your help!
