### ISSUE TITLE
Wrong results returned from bulk operations

### ISSUE THREAD

**Issue by joel-airspring** [mafintosh/mongojs#314]
We're using mongodb 2.6.x and recently upgraded from mongojs 0.18.2 to 2.3.0.

If you run bulk operations, the results returned in 2.3.0 seems wrong and doesn't match what we saw in the previous version we were using.  For example, if you make two calls, the first of which results in an upsert, and the second which does only a modify, you get the same result, even though they should be different.  Here's the sample code with two calls to Bulk.updateOne():

```javascript
var url = 'mongodb://localhost:27017/scratch';
var mongojs = require('mongojs');
var db = mongojs(url, null, { loggerLevel: 'debug' });
db.dropDatabase();
var coll = db.collection('dumpsters');
var bulk = coll.initializeUnorderedBulkOp();
bulk.find({ color: 'red' }).upsert().updateOne({ $set: { size: 'small' }});
bulk.execute(function(err, res) {
	console.log('find(red).upsert().updateOne() red small err ' + JSON.stringify(err, null, 2));
	console.log('find(red).upsert().updateOne() red small res ' + JSON.stringify(res, null, 2));
	var bulk2 = coll.initializeUnorderedBulkOp();
	bulk2.find({ color: 'red' }).upsert().updateOne({ $set: { size: 'medium' }});
	bulk2.execute(function(err, res) {
		console.log('find(red).updateOne() medium err ' + JSON.stringify(err, null, 2));
		console.log('find(red).updateOne() medium res ' + JSON.stringify(res, null, 2));
		db.close();
	});
});
```
 
Here's the 2.3.0 results:

```
find(red).upsert().updateOne() red small res {
  "writeErrors": [],
  "writeConcernErrors": [],
  "nInserted": 0,
  "nUpserted": 1,
  "nMatched": 0,
  "nModified": 0,
  "nRemoved": 0,
  "upserted": [],
  "ok": 1
```
and
```
find(red).updateOne() medium res {
  "writeErrors": [],
  "writeConcernErrors": [],
  "nInserted": 0,
  "nUpserted": 1,
  "nMatched": 0,
  "nModified": 0,
  "nRemoved": 0,
  "upserted": [],
  "ok": 1
}
```
As you can see, they're identical even though the operation result is different if you look in the server logs.  For the record, even though the results returned are wrong, the database is updated correctly.

Here's the result from 0.18.2, which matches what I would expect and matches what the server logs show (and matches the REPL if you do the commands there):
```
find(red).upsert().updateOne() red small res {
  "ok": 1,
  "writeErrors": [],
  "writeConcernErrors": [],
  "nInserted": 0,
  "nUpserted": 1,
  "nMatched": 0,
  "nModified": 0,
  "nRemoved": 0,
  "upserted": [
    {
      "index": 0,
      "_id": "57764873f765d5de9d30ceae"
    }
  ]
}
```
and 
```
find(red).updateOne() medium res {
  "ok": 1,
  "writeErrors": [],
  "writeConcernErrors": [],
  "nInserted": 0,
  "nUpserted": 0,
  "nMatched": 1,
  "nModified": 1,
  "nRemoved": 0,
  "upserted": []
}
```

I noticed that in 0.18.2, after a result is returned from the server, mongojs processes that result with a call to mergeBatchResults(), but does not make a similar call in 2.3.0.  Perhaps this needs to happen?

mergeBatchResults can be found in mongojs/node_modules/mongodb/lib/mongodb/collection/batch/common.js

**Comment by chriswininger** [comment]
There also seems to be problem with error handling in bulk updates, for example if I have a field called uid which I have defined as an index with unique values and I do something like

`
// add an entry with uid 1
db.collection('airspring.DataDictionary').insert({ id: '1', val: 'anything', uid: '1' }, function(err, status) {
     console.log('complete, error: ' + JSON.stringify(err) + ', status: ' + JSON.stringify(status));
});

// try to insert a second entry with same uid
var bulk = db.collection('airspring.DataDictionary').initializeUnorderedBulkOp();
bulk.find({ id: '2' }).upsert().updateOne({ id: '2', val: 'anything else', uid: '1' });
bulk.execute(function(err, status) { console.log('complete, error: ' + JSON.stringify( err) + ', status: ' + JSON.stringify(status) ); });
`

The bulk update callback will not return anything under error and writeErrors and writeConcernErrors are both null, but of course nothing was added because uid 1 violates the unique key constraint.

If I were to do

`
db.collection('airspring.DataDictionary').update({ id: '2' }, { id: '2', val: 'anything else', uid: '1' }, { upsert: true }, function(err, status) { console.log('complete, error: ' + JSON.stringify( err) + ', status: ' + JSON.stringify(status) ); });
`

I will correctly get an error message

**Comment by chriswininger** [comment]
Note if I try the above direct against my mongo cli I get an error message in the writeErrors array under the status object in the callback which is what I would expect the mongojs callback to return

**Comment by joel-airspring** [comment]
I no longer have need of this fix.
