### ISSUE TITLE
Passport adapter

### ISSUE THREAD

**Issue by askucher** [mafintosh/mongojs#315]
Hi 

Do you have mongojs templates for passportjs

I can find only for mongoose . I don't like this sh..t

**Comment by michaelguild13** [comment]
Passport is just a middleware. You should be able to find your answer in this code base. It's the official passport express 4 example.
https://github.com/passport/express-4.x-local-example

This is an example of where you would put mongojs:
https://github.com/passport/express-4.x-local-example/blob/master/server.js#L15

@askucher also please close this ticket since it's not a real issue :P
